spring:
  main:
    allow-bean-definition-overriding: true
  config:
    import: optional:configserver:http://localhost:8888
  application:
    name: msvc-Doctor
  datasource:
    password:
    url: jdbc:mysql://127.0.0.1:3306/citasmedicas
    username: root
