server:
  port: 7090
spring:
  application:
    name: msvc-paciente

eureka:
  instance:
    hostname: msvc-eureka
  client:
    service-url:
      defaultZone: http://localhost:7092/eureka