server:
  port: 7070
spring:
  application:
    name : msvc-gateway
    cloud:
      gateway:
        discovery:
           locator:
             enable: true
        routes:
        - id: pacientes
          uri: http://localhost:8081
          predicates:
            - Path=/api/v1/pacientes/**
        - id: especialidades
          uri: http://localhost:7090
          predicates:
            - Path=/api/v1/especialidades/**
        - id: doctores
          uri: http://localhost:8083
          predicates:
            - Path=/api/v1/doctores/**
        - id: tipocitas
          uri: http://localhost:8085
          predicates:
            - Path=/api/v1/tipocitas/**
eureka:
  intance:
    hotname: eureka-server
    client :
      register-with-eureka: false
      fetch_registry: true
      service-url :
       defaultZone: http://localhost:7092/eureka