FROM openjdk:17

WORKDIR /app

COPY ./CitasMedicas-Especialidades/target/CitasMedicas-Especialidades-0.0.1-SNAPSHOT.jar .

EXPOSE 7095

CMD ["java","-jar", "CitasMedicas-Especialidades-0.0.1-SNAPSHOT.jar"]