FROM openjdk:17

WORKDIR /app

COPY ./CitasMedicas-TipoDeCitas/target/CitasMedicas-TipoDeCitas-0.0.1-SNAPSHOT.jar .

EXPOSE 7090

CMD ["java","-jar", "CitasMedicas-TipoDeCitas-0.0.1-SNAPSHOT.jar"]