server:
  port: 7080

spring:
  application:
    name: msvc-gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: students
          uri: http://localhost:7090
          predicates:
            - Path=/api/v1/student/**
        - id: courses
          uri: http://localhost:7091
          predicates:
            - Path=/api/v1/course/**

eureka:
  instance:
    hostname: eureka-server
  client:
    register-with-eureka: false
    fetch-registry: true
    server-url:
      defaultZone: http://msvc-eureka:${server.port}/eureka/
